#!/usr/bin/python3

import sys
if len(sys.argv) > 1:
    from tiliadoweb.backend import main, log
    log("+ %s" % sys.argv)
    main()
    sys.exit(0)

import os
from gi.repository import Gtk

win = Gtk.Window()
win.set_title("Tiliado Repositories")
win.set_icon_name("system-software-install")
win.set_default_size(500, 400)
win.connect("delete-event", Gtk.main_quit)

from tiliadoweb.installer import Installer
from tiliadoweb.api import TiliadoApi
from tiliadoweb.config import PROTOCOL, HOST, SERVER, PASSWORD_RESET_PATH,SIGN_UP_PATH, \
API_PATH, API_AUTH
from tiliadoweb.gui import \
    LoginPage, RepositoriesPage, ComponentsPage, ProductsPage, SummaryPage, ProgressPage
from tiliadoweb.dists import guess_dist

login_page = LoginPage(SERVER + PASSWORD_RESET_PATH, SERVER + SIGN_UP_PATH)
login_page.show()

repositories_page = RepositoriesPage()
components_page = ComponentsPage(guess_dist())
products_page = ProductsPage()
summary_page = SummaryPage()
progress_page = ProgressPage()

api = TiliadoApi(SERVER, API_PATH, API_AUTH)
stack = Gtk.Stack(vexpand=True, hexpand=True)
win.add(stack)
stack.show()

try:
    stack.set_transition_duration(2 * stack.get_transition_duration())
    stack.set_transition_type(Gtk.StackTransitionType.SLIDE_LEFT_RIGHT)
except AttributeError:
    pass

from xdg import BaseDirectory
config_dir = BaseDirectory.save_config_path("tiliado")
installer = os.path.abspath(__file__)
installer = Installer(api, installer, config_dir, stack, login_page, repositories_page, components_page, products_page, summary_page, progress_page)

win.present()
Gtk.main()
