#!/usr/bin/python3

from gi.repository import Gtk

win = Gtk.Window()
win.set_title("Tiliado Repositories")
win.set_icon_name("system-software-install")
win.set_default_size(500, 400)
win.connect("delete-event", Gtk.main_quit)

from tiliadoweb.installer import Installer
from tiliadoweb.api import TiliadoApi
from tiliadoweb import DEVEL_SERVER, DEFAULT_PASSWORD_RESET_PATH, DEFAULT_SIGN_UP_PATH, \
DEFAULT_API_PATH, DEFAULT_API_AUTH
from tiliadoweb.gui import LoginPage, RepositoriesPage, ComponentsPage, SummaryPage
from tiliadoweb.dists import guess_dist

login_page = LoginPage(DEVEL_SERVER + DEFAULT_PASSWORD_RESET_PATH, DEVEL_SERVER + DEFAULT_SIGN_UP_PATH)
login_page.show()

repositories_page = RepositoriesPage()
components_page = ComponentsPage(guess_dist())
summary_page = SummaryPage()

api = TiliadoApi(DEVEL_SERVER, DEFAULT_API_PATH, DEFAULT_API_AUTH)
stack = Gtk.Stack(vexpand=True, hexpand=True)
win.add(stack)
stack.show()

from xdg import BaseDirectory
config_dir = BaseDirectory.save_config_path("tiliado")
installer = Installer(api, config_dir, stack, login_page, repositories_page, components_page, summary_page)

win.present()
Gtk.main()
