DEVEL_SERVER = "http://127.0.0.1:8000/"
DEFAULT_SIGN_UP_PATH = "accounts/signup/"
DEFAULT_PASSWORD_RESET_PATH = "accounts/password/reset/"
DEFAULT_API_PATH = "api/"
DEFAULT_API_AUTH = "api-auth/obtain-token/"
